### ISSUE TITLE
SIGSEGV on launch (Fedora Linux)

### ISSUE THREAD

**Issue by patrickwhelan99** [xaos-project/XaoS#205]
**Describe the bug**
On launch program exits with 
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff710f9a8 in __memset_avx2_unaligned_erms () from /lib64/libc.so.6
```

Stack trace
```
(gdb) bt
#0  0x00007ffff710f9a8 in __memset_avx2_unaligned_erms () at /lib64/libc.so.6
#1  0x00005555555cb0ef in memset (__len=7084, __ch=0, __dest=<optimized out>)
    at /usr/include/bits/string_fortified.h:71
#2  clear_image (img=0x555555657030) at image.c:269
#3  0x00005555555b766e in do_fractal (f=0x555555656370, flags=0, time=<optimized out>) at zoom.c:1554
#4  0x00005555555735a5 in uih_do_fractal (c=0x55555565b760) at ui_helper.c:983
#5  0x000055555556192d in ui_mainloop (loop=1) at ui.c:1728
#6  main (argc=<optimized out>, argv=<optimized out>) at ui.c:1555

```
**To Reproduce**
Install from Fedora repo

```
Installed Packages
Name         : xaos
Version      : 3.6
Release      : 12.fc32
Architecture : x86_64
Size         : 2.2 M
Source       : xaos-3.6-12.fc32.src.rpm
Repository   : @System
From repo    : fedora
```

**Desktop (please complete the following information):**
 - OS: Fedora 32

**Comment by kanurag94** [comment]
I think this is related https://stackoverflow.com/questions/12625841/linux-error-with-libc-so-6
It's better to compile 4.2 on your machine.
Maybe we can treat this bug as a request for .rpm of xaos 4.2
